### ISSUE TITLE
Recent update to pfsense changed acme.inc format

### ISSUE THREAD

**Issue by Trebacz** [blueslow/sslcertzoneedit#12]
I made the modification below to /usr/local/pkg/acme/acme.inc on pfsense around line 2750 (just before "//TODO add more challenge validation types" comment:

`$acme_domain_validation_method['dns_zoneedit'] = [`
`        'name' => 'DNS-Zoneedit',`
`        'fields' => [`
`                'ZONEEDIT_ID' => [`
`                        'name' => 'zoneedit_id',`
`                        'description' => 'ZONEEDIT ID',`
`                        'columnheader' => 'ID',`
`                        'type' => 'textbox',`
`                ],`
`                'ZONEEDIT_Token' => [`
`                        'name' => 'zoneedit_token',`
`                        'description' => 'ZONEEDIT Token',`
`                        'columnheader' => 'Token',`
`                        'type' => 'textbox',`
`                ],`
`        ]`
`];`

**Comment by blueslow** [comment]
Thnaks updated files according to acme.in format changes
