### ISSUE TITLE
add challenge to acme

### ISSUE THREAD

**Issue by ddt3** [blueslow/sslcertzoneedit#3]
Hello,

I have created: [#3950](https://github.com/acmesh-official/acme.sh/issues/3950)
Would be nice if your created dns challenge could be added to acme. Maybe by doing a pull request there?

**Comment by blueslow** [comment]
Hello,
Thank you for proposing that. But until there is a delete endpoint at zoneedit which is out of my control, I'm not prepared to do a pull request to add challenge to acme at the time being.

**Comment by ddt3** [comment]
I understand! 
I have used your scripts from command line and found them helpful, thank you for your work . 
On other systems where acme is "part of the system" I went for the acmedns option as on those systems that is fully automated.

**Comment by blueslow** [comment]
Thank you, I'm  glad  that scripts provided you some help.
