### ISSUE TITLE
A few notes

### ISSUE THREAD

**Issue by sbn-purchark** [blueslow/sslcertzoneedit#7]
The first time I tried this, I did --test with -d <my.dom> -d <alt.my.dom>. It worked, but it failed to remove the TXT record for the alt domain even though there was NO error. Checking the code closer I noticed dns_zoneedit.sh is using _get for create and [_post for delete](https://github.com/blueslow/sslcertzoneedit/blob/main/dns_zoneedit.sh#L122) (["DELETE" != GET](https://github.com/blueslow/sslcertzoneedit/blob/main/dns_zoneedit.sh#L184)). I haven't been able to reproduce this, so _post IS working for delete most of the time (I've not tried it for create). You have "Replace the usage of the get method to post in order to get better protection of id and token." so I'm not sure if this is intentional?

If you tell ZoneEdit to delete a non-existent TXT record, it will report HTTP code 200, success. So that might give an idea on why the delete "failed successfully".

ZoneEdit is enforcing a minimum 10 second delay to create or delete TXT records with the same host name. This breaks wildcard support. I have an idea of how I would fix this in the code that isn't just a sleep 10. I haven't spent enough time learning acme.sh's hooks, but you might have a better idea of what acme.sh expects. I'm not entirely sure I will be using wildcards. My internal LAN has a lot of cname's so I thought it might be useful there, otherwise my external end points are limited.

OPNSense is a lot different than Pfsense, there is no inc file for instance. Not sure I will be running acme.sh there. I might just do a SSH deploy from another system.

https://github.com/opnsense/plugins/tree/master/security/acme-client/src/opnsense/mvc/app
Just grepping for "FreeDNS" for example...
```
./library/OPNsense/AcmeClient/LeValidation/DnsFreedns.php: * FreeDNS API
./controllers/OPNsense/AcmeClient/forms/dialogValidation.xml:        <label>FreeDNS</label>
./models/OPNsense/AcmeClient/AcmeClient.xml:                        <dns_freedns>FreeDNS</dns_freedns>
```

I appreciate your script. Regards.

**Comment by blueslow** [comment]
I have changed the GET to ADD in dns_zoneedit_add() and tested both with wildcard and without successfully under pfsense, there were no remaining text records at zoneedit. I have not tested to delete a none existing TXT with the script. On the other hand a failed deleting of a non existing txt will end up with intended dns txt records anyway. I do not think that ADD or GET matters. The initial version used GET, e.g. before txt-delete.php endpoint existed e.g. the function dns_zoneedit_rm always returned OK. The delete functionality was implemented just a few days ago and was test both standalone (by onley, see [location of acme inc](https://github.com/blueslow/sslcertzoneedit/issues?q=is%3Aissue+is%3Aclosed#:~:text=location%20of%20acme.inc)) and pfsense (by me). I have not been able to replicate the error.  I more thinking that the -d <my.dom> -d <alt.my.dom> ... -d <altn.my.dom>, e.g. the dual or more  domains in one invoke cause the problem. However I have no standalone installation to test against. 

One of my test used the following command (wildcard on subdomain):
`
/usr/local/pkg/acme/acme.sh  --issue  --domain '*.test2.example.com' --dns 'dns_zoneedit'  --home '/tmp/acme/test/' --accountconf '/tmp/acme/test/accountconf.conf' --force --reloadCmd '/tmp/acme/test/reloadcmd.sh' --log-level 3 --log '/tmp/acme/test/acme_issuecert.log'
Array
(
    [path] => /etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin/
    [PATH] => /etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin/
    [ZONEEDIT_ID] => some_user
    [ZONEEDIT_Token] => some_token
)
`
dns_zoneedit.sh have never been tested under OPNSense by me. A fast glance at the github opnsense looks like the acme dns function are written under php.

Regards

**Comment by sbn-purchark** [comment]
> A fast glance at the github opnsense looks like the acme dns function are written under php.

Management/Web interface of OPNSense is written in PHP like pfSense (unless that's changed). The os-acme-client plugin depends on the acme.sh package which gets installed alongside it. The dnsapi directory exists as usual, but the way to add additional dnsapi scripts (to the web interface) looks to be more involved.

I knew dns_zoneedit wasn't tested under OPNsense, I was just noting the differences in case you were interested. I imagine once delete is fully functional then dns_zoneedit can be added to acme.sh repo and will thus show up on OPNSense in the next release.

I will check out your change(s) and do more testing.

Thanks

**Comment by blueslow** [comment]
> Management/Web interface of OPNSense is written in PHP like pfSense (unless that's changed).

I  agree on that but I was taking a fast  look for something similar to acme.inc which is used in pfsense  to interface the dnsapi functions of acme.sh to the webgui but OPNSense seem to either have a xml file or several *.php for the dnsapi files, but I may be misstaken.

When the dns_zoneedit.sh have more runtime I may fork the official acme and do integration testing.

Regards

**Comment by sbn-purchark** [comment]
> One of my test used the following command (wildcard on subdomain):
> `/usr/local/pkg/acme/acme.sh  --issue  --domain '*.test2.example.com' --dns 'dns_zoneedit' ...` 

I made that same mistake. That attempts to create a cert for the "*" sub-domain. After seeing it create a *. directory I knew I probably did something wrong.

See https://github.com/acmesh-official/acme.sh#11-issue-wildcard-certificates

It'd probably be easy for them to detect and automatically do the right thing. (you meant to create a wildcard domain, right?)

I'm working on dns_zoneedit.sh now, I'll do a pull when I think it's all good.

**Comment by blueslow** [comment]
> (you meant to create a wildcard domain, right?)

Yes both wildcard domain and wildcard subdomain.

> I made that same mistake. 
> ..it create *.directory ...

I don't understand what you mean with the above? 

Because the below command is successful. No directories were created only dns entries existed before(except "*") and there were no remaining dns txt challenge entries remaining after command terminated. See [Redacted log file](https://github.com/blueslow/sslcertzoneedit/blob/main/wildcard_test2_example_com.log):  
> One of my test used the following command (wildcard on subdomain):
/usr/local/pkg/acme/acme.sh  --issue  --domain '*.test2.example.com' --dns 'dns_zoneedit'  --home '/tmp/acme/test/' --accountconf '/tmp/acme/test/accountconf.conf' --force --reloadCmd '/tmp/acme/test/reloadcmd.sh' --log-level 3 --log '/tmp/acme/test/acme_issuecert.log' Array ( [path] => /etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin/ [PATH] => /etc:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin/ [ZONEEDIT_ID] => some_user [ZONEEDIT_Token] => some_token )

`/usr/local/pkg/acme/acme.sh  --issue  --domain '*.example.com' --dns 'dns_zoneedit ...'  `
`/usr/local/pkg/acme/acme.sh  --issue  --domain 'whatever.example.com' --dns 'dns_zoneedit ...'  `
`/usr/local/pkg/acme/acme.sh  --issue  --domain 'adifferent.example.com' --dns 'dns_zoneedit ...'  `
 
However the following and similar combinations is not tested and probably not working:

```
/usr/local/pkg/acme/acme.sh  --issue  --domain 'whatever.example.com' --domain 'adifferent.example.com' --dns 'dns_zoneedit ...
```
or 
```
/usr/local/pkg/acme/acme.sh  --issue  --domain 'example.com' --domain '*.example.com' --dns 'dns_zoneedit ...
```

Regards

**Comment by sbn-purchark** [comment]
> > (you meant to create a wildcard domain, right?)
> 
> Yes both wildcard domain and wildcard subdomain.

Sorry, I was a bit joking about how acme.sh would/should react when given this situation. I'll try to be more clear next time.

> > I made that same mistake.
> > ..it create *.directory ...
> 
> I don't understand what you mean with the above?

If I specify \*.example.com as the only domain to issue, acme.sh will create a folder named \*.example.com (to store the cert/key). Because * means something special, it is best avoided in file/folder names and surely acme.sh wouldn't be doing that. I was right, I need to specify the \*.example.com as an alternative domain name (per the doc). For example, --domain "example.com" --domain "\*.example.com".

Does pfSense ask if you are trying to create a wildcard domain? Like a checkbox option that says "create wildcard domain"? OPNSense doesn't tell me how to create a wildcard domain exactly, I just have to know based on what acme.sh expects.

> `/usr/local/pkg/acme/acme.sh --issue --domain '*.example.com' --dns 'dns_zoneedit ...' `

That won't create a proper wildcard certificate. To create a wildcard certificate, two TXT records with different data, but with the same host name must be created.

> However the following and similar combinations is not tested and probably not working:
> 
> ```
> /usr/local/pkg/acme/acme.sh  --issue  --domain 'whatever.example.com' --domain 'adifferent.example.com' --dns 'dns_zoneedit ...
> ```

It was working for me (without modifications) except for that one fluke. I'll be re-testing everything when I'm satisfied with my test branch.

> ```
> /usr/local/pkg/acme/acme.sh  --issue  --domain 'example.com' --domain '*.example.com' --dns 'dns_zoneedit ...
> ```

This is where I ran into that 10s limitation. I'm working on it and I'll keep you posted.

Regards

**Comment by sbn-purchark** [comment]
If you're interested to see my progress, https://github.com/blueslow/sslcertzoneedit/compare/main...sbn-purchark:sslcertzoneedit:test

Tested functional for the most basic cert issue on staging. I was just making it less confusing before I attempted something more complex.

**Comment by blueslow** [comment]
> That won't create a proper wildcard certificate. To create a wildcard certificate, two TXT records with different data, but with the same host name must be created.

I agree with you that it is not a complete wildcard domain or wildcard subdomain. Pfsense do not ask if its wildcard. Instead one add several  qualified domain names to include in the certificate.  The created certificate files are written to files named according  to title given in the webgui.

Your work looks good.
Please keep me posted on your progress.

Regards

**Comment by sbn-purchark** [comment]
I think I found a bug with their delete endpoint, it fails to remove every few TXT records when done in quick succession. Just a 1 second delay was enough, I'll be doing 2 seconds to be safe. I've reported it on the ZE forum thread.

I have working code to implement Zoneedit's rate limiting, so it's starting to shape up.

**Comment by blueslow** [comment]
Good work.
I guess that it will take some time before Zoneedit address this.

When you feel  that your improvements are reasonable stable  pleas do a pull request and I will merge and test under pfsense.

Regards

**Comment by sbn-purchark** [comment]
I think I got it. Took a bit before I was happy with the fault tolerance in case the expected API responses change (especially during an automatic renewal).

**Comment by sbn-purchark** [comment]
Annnd it didn't help that a logging bug in acme.sh was messing with me. I'm doing the PULL (https://github.com/blueslow/sslcertzoneedit/pull/8) now. Feel free to test it out.

Noticed while testing that ZE's txt endpoints allow modifying non-acme TXT records, bit of a security risk considering the types of records being stored there.

I might take a break for a bit, but I do plan to go back over the integration requirements more closely.

**Comment by blueslow** [comment]
I have merged and tested under pfsense. I fixed  spelling  and updated the README.md with aknowledgements.

Regarding the security risk it is important that the script, id, and token are kept safe.

Good work , I close the issue.
