### ISSUE TITLE
acme.sh default certifier has changed to ZeroSSL

### ISSUE THREAD

**Issue by atol71** [blueslow/sslcertzoneedit#9]
Hi,
If one want's to use Letsencrypt for certification a command:
`acme.sh --set-default-ca letsencrypt`
One could add it to readme information.

Keep those TPS cover sheet reports coming!
SH

**Comment by sbn-purchark** [comment]
https://github.com/sbn-purchark/sslcertzoneedit

Added it to my fork so I don't forget. I switched to letsencrypt pretty quick because ZeroSSL's servers were being unreliable when testing my changes to dns_zoneedit.sh.

**Comment by blueslow** [comment]
Updated the README.md
